### ISSUE TITLE
The input to the decoder is strange

### ISSUE THREAD

**Issue by ShengleiH** [jingxil/Pointer-Networks#2]
Hello, thanks for sharing your codes. I have a question after reading your code.

Why do you use the scores rather than the probabilities of alignments?
In the paper, authors use the softmax results of alignments, which should be probabilities.

**Comment by jingxil** [comment]
Hi, ShengleiH
We only want to pick the one with the highest value. There is no need to calculate the probabilities. Because the largest element in the input remains the  largest element after the softmax function is applied which means these two work equivalently.

**Comment by ShengleiH** [comment]
Your codes helped my a lot. Thank you :)

**Comment by jingxil** [comment]
you are very welcome :)
