### ISSUE TITLE
Initial state of the decoder

### ISSUE THREAD

**Issue by joshinh** [jingxil/Pointer-Networks#4]
Hi,

Firstly, thanks a lot for sharing for your code. 

I had a question regarding the initial state of the decoder. I see that it is currently initialized with zero_state. Shouldn't the decoder initial state be initialized with the final state of the encoder? Please do correct me if I am wrong

**Comment by jingxil** [comment]
Sure, it would have a slightly better performance (compared and verified in other projects). At that time  I initialized the decoder state with zero for simplicity since the `memory` has provided necessary  information.
